<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Plumbing and heating specialists based in Doncaster</title>

        <link rel="stylesheet" href="/css/style.css" type="text/css" media="screen">
        <link rel="icon" href="/images/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon" />
    </head>
    <body id="page1">
        <header>
            <div class="row-top">
                <div class="main">
                    <div class="container_12">
                        <div class="grid_6">
                            <h1><a href="<?php echo $this->url('page'); ?>">Pete the Plumber</a></h1>
                        </div>
                        <div class="grid_6 omega alignright">
                            <p class="contacts white"><span>Call:</span> 07876 367187</p>
                            <p class="contacts white"><span>Email:</span> pete@petetheplumberuk.com</p>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
            <div class="row-nav">
                <div class="main">
                    <nav>
                        <?php
                        echo $this->navigation(
                        $this->navigation('Navigation')->getContainer()
                        )->menu()->setUlClass('sf-menu responsive-menu');
                        ?>
                    </nav>
                    <div class="clear"></div>
                </div>
            </div>
        </header>
        <?php
        /*
          <div class="box-slider">
          <div class="flexslider">
          <ul class="slides">
          <li> <img src="images/slide-1.jpg" alt="" /> </li>
          <li> <img src="images/slide-2.jpg"  alt=""/></li>
          <li> <img src="images/slide-3.jpg" alt="" /></li>
          </ul>
          </div>
          </div>
         */
        ?>
        <section id="content">
            <?php echo $this->content; ?>
        </section>
        <footer>
            <div class="main">
                <div class="privacy">
                    <a href="<?php echo $this->url('page'); ?>" class="logo-footer">
                        Pete the Plumber
                    </a> | &copy; <?php echo date('Y'); ?>
                </div>
                <?php
                /*
                  <div class="soc">
                  <a href="#"><img src="images/icon-1.gif" alt="" /></a>
                  <a href="#"><img src="images/icon-2.gif" alt="" /></a>
                  <a href="#"><img src="images/icon-3.gif" alt="" /></a>
                  </div>
                 */
                ?>
            </div>
        </footer>
    </body>
</html>
