<div class="container_12">
    <div class="grid_12">
        <p>More information coming soon</p>
        <div class="border-horiz"></div>
    </div>
    <div class="clear"></div>
    <article class="grid_3">
        <?php
        /*
        <figure class="box-img">
            <img src="images/page1-img1.jpg " alt="" />
        </figure>
        */
        ?>
        <h4 class="border-bot p16">Boiler replacements</h4>
        <p class="line-h">More information coming soon.</p>
        <a href="#" class="button"><span></span>read more</a>
    </article>
    <article class="grid_3">
        <?php
        /*
        <figure class="box-img">
            <img src="images/page1-img1.jpg " alt="" />
        </figure>
        */
        ?>
        <h4 class="border-bot p16">Underfloor heating</h4>
        <p class="line-h">More information coming soon.</p>
        <a href="#" class="button"><span></span>read more</a>
    </article>
    <article class="grid_3">
        <?php
        /*
        <figure class="box-img">
            <img src="images/page1-img1.jpg " alt="" />
        </figure>
        */
        ?>
        <h4 class="border-bot p16">Full central heating systems</h4>
        <p class="line-h">More information coming soon.</p>
        <a href="#" class="button"><span></span>read more</a>
    </article>
    <article class="grid_3">
        <?php
        /*
        <figure class="box-img">
            <img src="images/page1-img1.jpg " alt="" />
        </figure>
        */
        ?>
        <h4 class="border-bot p16">Other plumbing services</h4>
        <p class="line-h">More information coming soon.</p>
        <a href="#" class="button"><span></span>read more</a>
    </article>
    <div class="clear"></div>

    <div class="main">
        <div class="border-horiz"></div>
    </div>

    <?php
    /*
    <article class="grid_6">
        <div class="inner-1">
            <h3>Latest News</h3>
            <div class="wrapper">
                <div class="date-1">27<span>APR</span></div>
                <div class="overflow p4">
                    <h6 class="p0"><a href="#" >Duis posuere consectetur pellentesqe;</a></h6>
                    <div class="date-2 p5">April 27.03.12</div>
                </div>
            </div>

            <p class="p11">Sed nisi turpis, pellentesque at ultrices in, dapibus in magna. Nunc easi diam risus, placerat ut scelerisque et, suscipit eu ante. Nullam vitae dolor ullcper felises cursus gravida. Cras felis elit, pellentesqi amet. </p>
            <div class="border-horiz1"></div>
            <div class="wrapper">
                <div class="date-1">28<span>MAY</span></div>
                <div class="overflow p4">
                    <h6 class="p0"><a href="#" >Duis posuere consectetur pellentesqe;</a></h6>
                    <div class="date-2 p5">May 28.05.12</div>
                </div>
            </div>
            <p class="p11">Sed nisi turpis, pellentesque at ultrices in, dapibus in magna. Nunc easi diam risus, placerat ut scelerisque et, suscipit eu ante. Nullam vitae dolor ullcper felises cursus gravida. Cras felis elit, pellentesqi amet. </p>
        </div>
    </article>
    <article class="grid_6">
        <h3>Testimonials</h3>
        <div class="wrapper p3">
            <figure class="img-indent box-img"><img src="images/page1-img5.jpg " alt="" /></figure>
            <div class="overflow">
                <div class="box-quote">
                    <div class="name-date">James Rivoly&nbsp;  23.03.12</div>
                    <blockquote class="quote-1">Lorem ipsum dolor sit amet, consectetur is a adipiscing elit. Cras aliquam sollicitudin velit, blandit ornare urna aliquam. </blockquote>
                </div>
            </div>
        </div>
        <div class="wrapper padd-1">
            <figure class="img-indent-r box-img"><img src="images/page1-img6.jpg " alt="" /></figure>
            <div class="overflow">
                <div class="box-quote1">
                    <div class="name-date">Sara Techer&nbsp; 24.03.12</div>
                    <blockquote class="quote-1">Lorem ipsum dolor sit amet, consectetur is a adipiscing elit. Cras aliquam sollicitudin velit, blandit ornare urna aliquam. </blockquote>
                </div>
            </div>
        </div>
    </article>
    <div class="clear"></div>
    */
    ?>
</div>